// SampleCOMServer.idl : IDL source for SampleCOMServer
//

// This file will be processed by the MIDL tool to
// produce the type library (SampleCOMServer.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(0BC51E46-AC50-4B42-A800-BAD920736FCA),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISampleApartmentThreadedClass : IDispatch
{
	[id(1)] HRESULT Test(void);
};

[
	object,
	uuid(B4B37799-C3D3-4563-B044-FB10DCECE8B5),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISampleFreeThreadedClass : IDispatch
{
	[id(1)] HRESULT Test(void);
};

[
	object,
	uuid(85FDCD3F-9628-4394-B132-3097FC9529BA),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ISampleTestInterface : IDispatch
{
	[id(1)] HRESULT TestInterface(void);
};


[
	uuid(47D8F861-8023-4E58-88C6-A8E88BDAD337),
	version(1.0),
]
library SampleCOMServerLib
{
	importlib("stdole2.tlb");
	[
		uuid(234C84AD-FA3D-41C0-870B-028495B603A5)		
	]
	coclass SampleApartmentThreadedClass
	{
		[default] interface ISampleApartmentThreadedClass;
	};
	[
		uuid(64C146B4-FED7-4C09-885A-B62B1E604640)		
	]
	coclass SampleFreeThreadedClass
	{
		[default] interface ISampleFreeThreadedClass;
	};
};

